export const ADD_COMPANIES = 'ADD_COMPANIES';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const ADD_LEVELS = 'ADD_LEVELS';
export const ADD_SOCIAL_MEDIA = 'ADD_SOCIAL_MEDIA';
export const ADD_SOCIAL_MEDIA_TYPE = 'ADD_SOCIAL_MEDIA_TYPE';
export const ADD_TRIPS = 'ADD_TRIPS';
