export const urlCompanies = 'companies'
export const urlUsers = 'users'
export const urlSocial_medias = 'social_medias'
export const urlSocial_media_types = 'social_media_types'
export const urlTrips = 'trips'
export const urlLevels = 'levels'
export const urlLocations = 'locations'
